baseURL = 'https://rapture-rov.github.io/'
languageCode = 'en-us'
title = 'Rapture ROV'
theme = 'hyde'

[params]
  description = "High school ROV (Remotely Operated Underwater Vehicle) team from Turkey"
  themeColor = "theme-base-0d"

[Menus]
  main = [
    {Name = "About", URL = "https://rapture-rov.github.io/about/"},
    {Name = "GitHub", URL = "https://github.com/rapture-rov/"},
  ]

